[package]
name = "datagen"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
arrayvec = "0.7.8"
chess = { path = "../chess" }
chrono = "0.4.45"
clap = { version = "4.6.7", features = ["derive"] }
ctrlc = "3.5.2"
engine = { path = "../engine", features = ["datagen", "syzygy"] }
fastrand = "2.5.0"
humantime = "2.4.0"
nnue = { path = "../nnue" }

[features]
embed = ["nnue/embed"]
syzygy = ["engine/syzygy"]
