[workspace]
resolver = "2"
members = ["chess"]

[profile.release]
opt-level = 3
target-cpu = "native"
lto = "fat"
codegen-units = 1
panic = "abort"
overflow-checks = false
debug = false
rpath = false

[profile.bench]
inherits = "release"
overflow-checks = true

[profile.dev]
overflow-checks = true
