[package]
name = "engine"
version = "0.5.4"
edition = "2024"
authors = ["TheGogy"]

[lib]
doctest = false

[dependencies]
anyhow = "1.0.104"
chess = { path = "../chess" }
nnue = { path = "../nnue" }
utils = { path = "../utils" }

[build-dependencies]
bindgen = { version = "0.73.2", optional = true }
cc = { version = "1.4.7", optional = true }

[features]
datagen = []
nnz_logging = ["nnue/nnz_logging"]
syzygy = ["dep:bindgen", "dep:cc"]
tune = []
