[package]
name = "engine"
version = "0.4.3"
edition = "2024"
authors = ["TheGogy"]

[dependencies]
chess = { path = "../chess" }
utils = { path = "../utils" }
nnue = { path = "../nnue" }

[features]
tune = []
