[package]
name = "cli"
version = "0.0.1"
edition = "2024"
authors = ["TheGogy"]

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
engine = { path = "../engine" }
nnue = { path = "../nnue" }

[features]
embed = ["nnue/embed"]
embed_direct = ["nnue/embed_direct"]
nnz_logging = ["engine/nnz_logging", "nnue/nnz_logging"]
syzygy = ["engine/syzygy"]
tune = ["engine/tune"]
