[package]
name = "nnue"
version = "0.5.4"
edition = "2024"

[lib]
doctest = false

[[example]]
name = "find_nnz_ft_perm"
required-features = ["nnz_logging"]

[dependencies]
arrayvec = "0.7.8"
chess = { path = "../chess" }
rand = "0.10.2"
utils = { path = "../utils" }

[features]
embed = []
embed_direct = []
nnz_logging = []
